### ISSUE TITLE
Implement score for Stacking and Ensemble Learning

### ISSUE THREAD

**Issue by elopezfune** [sebp/scikit-survival#151]
Is it possible to implement the "score" for sksurv.meta.Stacking, sksurv.meta.EnsembleSelection and sksurv.meta.EnsembleSelectionRegressor, in order to measure the performance of the final model? So far I see developed the scorer_ for each individual model, but not for the final one after stacking.

**Comment by sebp** [comment]
For Stacking this can be added, because it's just a matter of calling the score function of the meta estimator. For EnsembleSelection, I'm not entirely sure, because not all models return the same type of prediction. For instance, `CoxPHSurvivalAnalysis` predicts a risk score, but `IPCRidge`'s predictions are on log-time. To compute the concordance index, we would need to know what type of predictions the ensemble members return, which currently is not possible.
