### ISSUE TITLE
Discuss/request: required y survival status can be 0/1 integer in addition to bool

### ISSUE THREAD

**Issue by pavopax** [sebp/scikit-survival#26]
Currently, outcome y is required to be a structured array as (event, time) with boolean event.

I'd like to discuss/request whether we can also accept a 0/1 integer event status, in addition to a boolean type.

Motivation:
- sometimes I analyze the dataset in R and sometimes in Python. R accepts both boolean and 0/1 integers in survival analysis (see [Surv's event](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/Surv.html)).

It would be a good bonus to have `sksurv` also support both dtypes. Curious about others' thoughts.

**Comment by region-spotteR** [comment]
Absolutely for it! I think am quite capable in programming. But I still have no clue, how to get to the structured arrays and I've been trying for a while now! I know my python-skills are a bit rusty - but not this much. If somebody could post quick minimal

**Comment by pavopax** [comment]
@region-spotteR I use a pandas dataframe -> structured array workflow. Say you have pandas `df` with 2 columns: `status` and `time`. Convert status to bool and then convert the 2 columns into structured array

    df.status = df.status.astype('bool')
    df.to_records(index=False)


to recap, the point of this thread is to discuss/request that we don't need the first line

**Comment by sebp** [comment]
> If somebody could post quick minimal example how you create this structured array from two lists, that would be very helpfu

I usually use numpy.fromiter as in [this line](https://github.com/sebp/scikit-survival/blob/8a6cb06a92b82d563edae5d4ccbf3a4775bc9a14/tests/test_coxph.py#L18).

It seems there are a couple of related issues,

1. Construction of structured array is not straight-forward.
2. Supporting passing a 2-column pandas DataFrame instead of structured array.
3. Allow for censoring indicator to be an array of 0/1 instead of boolean.

I believe it would be best to add a function equivalent to R's `Surv` that converts different inputs to the structured array format used internally.

**Comment by shahlaebrahimi** [comment]
@pavopax @sebp Hi
I would greatly appreciate if you could let me know whether this package could be used for discrete time survival analysis? I mean `xtcloglog`, `cloglog`, or `xtlogit `in [Stata](https://www.statalist.org/forums/forum/general-stata-discussion/general/632717-discrete-time-hazard-model-with-xtcloglog) or this [link](https://www.statalist.org/forums/forum/general-stata-discussion/general/1374269-survival-analysis-based-on-panel-data-with-discrete-and-continously-time-varying-covariates).

Thanks in advance.
Best regards,
