### ISSUE TITLE
ROC

### ISSUE THREAD

**Issue by 464hee** [sebp/scikit-survival#280]
I found that there is no support for survival analysis to plot ROC curves for the time being. Please, will the relevant ROC calculation function break new ground in future project work

**Comment by sebp** [comment]
In time-to-event analysis ROC curves are always time-dependent. Usually, the ROC is computed over hundreds of time points, therefore plotting them is always never done. Instead , the [integrated area under the curve](https://scikit-survival.readthedocs.io/en/latest/api/generated/sksurv.metrics.cumulative_dynamic_auc.html) is the preferred measure. Since plotting is almost never used, I have no plans to implement it.
