### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by ncdingari** [sebp/scikit-survival#3]
Unable to install on windows, do you have any prebuilt version with `whl`

I tried using `pip install scikit-survival`, having some build issues with C++ compiler. It would be great if you have `whl` file

**Comment by sebp** [comment]
Could you please post the error message here?

**Comment by sebp** [comment]
I fixed a problem with fmin and fmax not being available in commit 2bd9e5e0a3235b8ee911e49445eef485de697016.

Unfortunately, I was only able to build a whl for Python 3.4 due to cvxopt/cvxopt#94.

It would be great if you could give it a try and let me know if it works: https://ci.appveyor.com/project/sebp/scikit-survival/build/1.0.21/artifacts

**Comment by KOLANICH** [comment]
It doesn't. Still there are issues. I use the latest Anaconda on 32-bit win 7 with mingw32-w64 (it's a 32-bit compiler!) installed (from conda).

**Comment by KOLANICH** [comment]
The workaround is to remove linear_model folder and all its contents and remove its cython building from setup.py

**Comment by sebp** [comment]
Unfortunately, I don't have the resources to support 32bit builds. If you need a pre-compiled version for 64bit Windows, you can use conda: `conda install -c sebp scikit-survival`.

**Comment by region-spotteR** [comment]
On my windows computer, I had issues because the `ecos`-library didn't install. In the end I added every dependency using `pip` and for `ecos` I installed it manually using the python wheel
