### ISSUE TITLE
Possible improvement in documentation of Cumulative dynamic AUC

### ISSUE THREAD

**Issue by melodiemonod** [sebp/scikit-survival#425]
In the documentation https://scikit-survival.readthedocs.io/en/stable/api/generated/sksurv.metrics.cumulative_dynamic_auc.html

It would make the denominator more interpretable if it was written as $$(\sum_{i = 1}^n \sum_j^n  I(y_j > t) I(y_i \leq t) \omega_i)$$ instead of  $$(\sum_{i = 1}^n I(y_i > t))(\sum_i^n I(y_i \leq t) \omega_i)$$.

**Comment by sebp** [comment]
Mathematically, you are correct. I think it's easier to understand in its current form, because the ROC curve compares sensitivity and specificity. The first term $\sum_{i=1} I(y_i > t)$ is related to the denominator of the specificity, and the term $\sum_{i=1} I(y_i < t) \omega_i$ to the denominator specificity.
