### ISSUE TITLE
Error when running cross-validation example

### ISSUE THREAD

**Issue by paidi** [sebp/scikit-survival#47]
I'm trying to run the examples from this talk: https://k-d-w.org/slides/pyconuk-2017/

I'm getting an error when I run this code snippet

```python
from sksurv.datasets import load_breast_cancer
from sksurv.preprocessing import OneHotEncoder
from sksurv.linear_model import CoxnetSurvivalAnalysis
from sklearn.model_selection import GridSearchCV, KFold
X, y = load_breast_cancer()
Xt = OneHotEncoder().fit_transform(X)

cv = KFold(n_splits=5, shuffle=True, random_state=328)
coxnet = CoxnetSurvivalAnalysis(n_alphas=100,
    l1_ratio=1.0, alpha_min_ratio=0.01).fit(Xt, y)

gcv = GridSearchCV(coxnet,
    {"alphas": [[v] for v in coxnet.alphas_]},
    cv=cv).fit(Xt, y)
```

When I run this code, I get a failed assertion at https://github.com/sebp/scikit-survival/blob/71bba9353c8616e9d85949c16b70775f465d80df/sksurv/linear_model/coxnet.py#L192

It looks like something is going wrong with the optimisation and the coefficients are all 0 or nan.

**Comment by sebp** [comment]
Some alpha values are too low and result in large coefficients, which leads to numerical errors. This is also the case for R's glmnet package. Optimization is now aborted with an exception if coefficients get to large.

For the example to work, you need to call `GridSearchCV` with the `error_score` argument.

**Comment by paidi** [comment]
That's great. Thanks!

**Comment by hermidalc** [comment]
@sebp this is actually not the complete story, something else is going wrong with the implementation of Coxnet in scikit-survival.  I've been struggling with this for days trying to troubleshoot what is going on.

I can understand that the max and min alpha values are going to change a bit between calculating them on all of X and y on each CV training fold of X and y.  I initially thought this was the reason why I was getting "Numerical error... Consider increasing alpha" and on the opposite end "All coefficients are zero... Consider decreasing alpha".

But when I made a test and fit a model on all the data and also on each CV fold, printed the automatically generated alphas for each model, selected an alpha value that is right in the middle of all the model alpha ranges, and finally fit a model with that single alpha value, I still commonly get the the "Numerical error... Consider increasing alpha" error?  Something isn't right, do you know why?

I will post a reproducible example here in a bit.

**Comment by sebp** [comment]
If you could provide a minimal example, that would be very helpful.

**Comment by hermidalc** [comment]
> If you could provide a minimal example, that would be very helpful.

Here's the same example, simplifying without `GridSearchCV` and being more exact by using the `alphas_` for each CV fold:

```python
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sksurv.datasets import load_breast_cancer
from sksurv.preprocessing import OneHotEncoder
from sksurv.linear_model import CoxnetSurvivalAnalysis

X, y = load_breast_cancer()

pipe = Pipeline([('one', OneHotEncoder()),
                 ('cox', CoxnetSurvivalAnalysis(alpha_min_ratio=0.01))])

cv = KFold(n_splits=5, shuffle=True, random_state=777)
for train_idxs, _ in cv.split(X, y):
    pipe.set_params(cox__alphas=None)
    pipe.fit(X.iloc[train_idxs], y[train_idxs])
    alphas = pipe[-1].alphas_
    for alpha in alphas:
        print(alpha)
        pipe.set_params(cox__alphas=[alpha])
        pipe.fit(X.iloc[train_idxs], y[train_idxs])
```
You will see above that when `alphas=None` your Coxnet implementation will generate the alpha path and supposedly fits through the entire sequence of `alphas_`.  There are no convergence warnings or numerical errors.

But when you take those same `alphas_` and fit them individually on the same pipeline and data from which each were generated you eventually get the:
```python
ArithmeticError: Numerical error, because weights are too large. Consider increasing alpha.
```

I believe this has to do with selection of `alpha_min_ratio` for the dataset.  In the _Regularization Paths for Cox’s Proportional Hazards Model via Coordinate Descent_ paper they describe that even though one specifies `n_alphas=100` you do not fit all the alphas down through the unregularized solution.

It seems to me that when `alphas=None` your Coxnet implementation silently and appropriately stops fitting down the alpha path at a certain point?  But when you individually fit any smaller alpha past that point you the numerical error?

**Comment by hermidalc** [comment]
@sebp in my further testing and use IMHO I don't think you necessarily need to do anything about this.  For the particular dataset being used and the relationship between n_samples and n_features in that dataset `alpha_min_ratio` must be specified appropriately.  For example, I typically deal with very high-dimensional datasets where n_samples << n_features therefore I need to usually specify an `alpha_min_ratio=0.1 or 0.125` and then I do not run into the `Numerical error, because weights are too large. Consider increasing alpha.` error when fitting each individual alpha from `alphas_`.

Just what is initially confusing to users of `CoxnetSurvivalAnalysis` is that when you specify e.g. `alpha_min_ratio=0.01` and leave `alphas=None` and fit very high-dimensional data to automatically generate the `alphas_` path it will fit without any warnings or errors.  But then when you individually take each alpha from `alphas_` and fit on the same data you will typically get the numerical error as you go down to smaller alphas because the `alpha_min_ratio` you initially selected wasn't large enough even though the initial fit to get `alphas_` didn't have a problem.  Hope that makes sense for other users that come here.

**Comment by sebp** [comment]
> It seems to me that when alphas=None your Coxnet implementation silently and appropriately stops fitting down the alpha path at a certain point? But when you individually fit any smaller alpha past that point you the numerical error?

That's absolutely correct. When fitting a path of alpha values and alpha becomes to small, the optimizer essentially stops. If instead you ask to fit a model for the same alpha (and nothing else), it has no way of knowing that it is too small, because it couldn't try bigger values. That's why you will get an error.

I think it would be a good idea to set `alpha_min_ratio` depending on `n_samples` and `n_features` as suggested in #41.
