### ISSUE TITLE
ValueError:all times must be within follow-up time of test data:

### ISSUE THREAD

**Issue by WellJoea** [sebp/scikit-survival#86]
raise ValueError(
            'all times must be within follow-up time of test data: [{}; {}['.format(
                test_time.min(), test_time.max()))
how to use cumulative_dynamic_auc in cross valiation split data, as I cannot control the max and min value in train data at each fold in CV .

**Comment by sebp** [comment]
Can you please post a minimal working example that demonstrates what you want to achieve and results in the the problem above?

**Comment by sebp** [comment]
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Comment by belapyc** [comment]
I have the same issue:

```
rsf = RandomSurvivalForest(n_estimators=1000,
                           min_samples_split=10,
                           min_samples_leaf=15,
                           max_features="sqrt",
                           n_jobs=-1,
                           random_state=random_state)

rsf.fit(encoded_features_df, data_y_struct_array)

times = np.percentile(data_y[data_y['status'] == True]['time_to_event'], np.linspace(5, 81, 15))
print(times)

chf_funcs = rsf.predict_cumulative_hazard_function(X_test, return_array=False)

rsf_risk_scores = np.row_stack([chf(times) for chf in chf_funcs])

rsf_auc, rsf_mean_auc = cumulative_dynamic_auc(
    y_train, y_test, rsf_risk_scores, times
)
```

Gives me the error:

```
ValueError: all times must be within follow-up time of test data: [56.0; 291.0[
```

**Comment by AnkushJamthikar** [comment]
[belapyc](https://github.com/belapyc) have you resolved this issue?

**Comment by AnkushJamthikar** [comment]
I am also facing the same issue when computing the `times` for `cumulative_dynamic_auc` function. Following is what I am getting,

`ValueError: all times must be within follow-up time of test data: [2.0; 1195.595139[`

Any solution this problem?

**Comment by maguileracanon** [comment]
I am having the same issue when the test data and the train data have different ranges for Time

**Comment by sebp** [comment]
There error occurs because the `times` argument contains one or more time points that are not in the interval that the survival functions in `survival_test` cover. You cannot compute a Brier score for a time point that is not covered by any survival function estimated on the test data.

I'm not aware of a general solution, because it depends on the characteristics of the particular dataset (size, amount of censoring). You should check which time intervals the survival functions in your test data cover and compare it with `times`. This should give you a clue on how to adjust `times`.
