### ISSUE TITLE
Build error on windows: unable to find vcarsall.bat

### ISSUE THREAD

**Issue by scienceaiden** [sebp/scikit-survival#9]
Hello,
I have Python 3.6 on Windows 10 and VS 2012. I assume I should be able to use it but get error running below command:

`
from sksurv.svm import FastSurvivalSVM
`

the error message:
![image](https://user-images.githubusercontent.com/25181661/30501321-02ed2fd2-9a30-11e7-9751-4d18dc81cea2.png)

i tried to modify _msvccompiler.py but it seems like it is taking the setting for VS from registry.

Please advise!
Thank you

**Comment by sebp** [comment]
Currently, only Python 3.4 is fully supported on Windows due to cvxopt/cvxopt#94, therefore I haven't checked other versions. If I find some time, I'll try to create a Windows build with cxvopt support disabled.

**Comment by scienceaiden** [comment]
Thank you - looking forward to it

**Comment by scienceaiden** [comment]
Based on the description it is only for Linux and Mac - please confirm

**Comment by sebp** [comment]
I was able to create a window build for Python 3.5 and 3.6 without cvxopt support.

I didn't encounter the error you encountered, it might be related to using VS 2012 instead of VS 2015, which is [needed for Python 3.5 and 3.6](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Visual_C.2B-.2B-_Build_Tools_2015_.28x86.2C_x64.2C_ARM.29).

Could you please try whether the pre-built Windows package from https://ci.appveyor.com/project/sebp/scikit-survival/build/job/81y016cbeunhhw20/artifacts works for you?

**Comment by scienceaiden** [comment]
Fantastic sebp - after installing vs2015 and running your exe, python code recognize FastKernelSurvivalSVM and others. thank you!
