### ISSUE TITLE
Custom Prediction Interval for predict_survival_function

### ISSUE THREAD

**Issue by MaxPooling** [sebp/scikit-survival#99]
Hi, @sebp 

I understand that the prediction interval for predict_survival_function is constructed by the unique number of uncensored events and predictions correspond to survival probabilities at these events in descending order.

My question: Is there a way to predict the survival function for a given range like 1-1000 days (Intrapolate + Extrapolate)? 

Background: I have two observation groups that I need to train separately, but I need to build a combined predictive application. So the interval of the survival function should be consistent across datasets to build comparisons.

This somewhat refers to #30, but I think the answer does not provide a solution. Testing it, it only extracts predictions from the existing range.

Thanks  in advance!

**Comment by sebp** [comment]
I assume you are referring to `CoxPHSurvivalAnalysis`. In general, this is not possible without making some sort of assumption about the baseline hazard function in the future. The only situation in which we can estimate the survival function up to infinity is if an event occurs for all samples in the dataset. In this situation, the survival function will remain zero up to infinity. If not everyone experienced an event up to the last observed time, we don't really now what the future would look like and the survival function beyond the time point is undefined. Of course, you can just assume a particular form of the baseline hazard (e.g. it stays constant), which would allow you to compute the survival function. In my opinion, this would be more sensible when dealing with parametric survival models rather than semi-parametric CoxPH. Unfortunately, the only parametric model currently implement is `IPCRidge`, which behaves quite different from CoxPH.

What you could try in your particular case is estimating the baseline hazard function from the complete data using `sksurv.linear_model.coxph.BreslowEstimator` and then plugging the risk score estimated by CoxPH from your individual models into `get_survival_function`. That's essentially what `CoxPHSurvivalAnalysis.predict_survival_function` does.
